version: '2'

services: 
  plat-app: 
    image: jyh-test/plat-app
    restart: always
    ports: 
      - "8313:8313"
      #- "28313:28313"
    logging:
      driver: fluentd
      options: 
        tag: "docker.{{.ID}}"
        fluentd-address: "192.168.3.5:24224"
    #environment: 
      #- SPRING_PROFILES_ACTIVE=dev
      #- DUBBO_IP_TO_REGISTRY=192.168.3.5
      #- DUBBO_PORT_TO_REGISTRY=28313
